dbt_transformation:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'D:/.Dominika/Projekty informatyczne/projekt_nieruchomości/nieruchomosci_uk.db'
      extensions:
        - httpfs
        - parquet